/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.archolding.view.buscadores;

import com.archolding.dao.MovimientoStockDao;
import com.archolding.dao.ProductosDao;
import com.archolding.model.Dproductos;
import com.archolding.model.table.ModeloTablaBuscadorProducto;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.TableColumnModel;
import com.archolding.interfaces.InterfaceBuscadorProducto;
import com.archolding.model.Mstock;
import com.archolding.model.table.ModeloTablaMasCodigos;
import com.archolding.model.table.ModeloTablaVerStock;
import com.archolding.util.Utilidad;

/**
 *
 * @author Jorge Fabio
 */
public class FormularioBuscadorProductos extends javax.swing.JDialog {

    /**
     * Creates new form FormulariosBuscadorProductos
     */
    private Dproductos productos;
    private ProductosDao dao;
    private ModeloTablaBuscadorProducto mtDproductos;
    private ModeloTablaVerStock mtVerStock;
    private List<Dproductos> lista;
    private String accion;
    private InterfaceBuscadorProducto interfaceBuscadorProducto;
    private MovimientoStockDao stockDao;
    private Mstock stock;
    private List<Mstock> listaStock;
    private ModeloTablaMasCodigos mtVerMasCodigos;

    public void setInterfaceBuscadorProducto(InterfaceBuscadorProducto interfaceBuscadorProducto) {
        this.interfaceBuscadorProducto = interfaceBuscadorProducto;
    }

    public FormularioBuscadorProductos() {
        initComponents();
        setLocationRelativeTo(this);
        TableColumnModel columnModel = tableProductos.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(400);
        tfDescripcion.requestFocus();
        activarPanelStock(false);
        Utilidad.salirConEscapeBuscador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesAnexo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        mtDproductos = new ModeloTablaBuscadorProducto();
        tableProductos = new javax.swing.JTable();
        chkProveedores = new javax.swing.JCheckBox();
        panelProveedores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        panelAnexos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaStockCodigos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        jrVerStock = new javax.swing.JRadioButton();
        jrVerCodigos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Productos");
        setModal(true);

        tableProductos.setModel(mtDproductos);
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        tableProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableProductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        chkProveedores.setText("Mostrar Proveedores");

        panelProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProveedores.setEnabled(false);
        jScrollPane2.setViewportView(tablaProveedores);

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAnexos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaStockCodigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaStockCodigos);

        javax.swing.GroupLayout panelAnexosLayout = new javax.swing.GroupLayout(panelAnexos);
        panelAnexos.setLayout(panelAnexosLayout);
        panelAnexosLayout.setHorizontalGroup(
            panelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnexosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAnexosLayout.setVerticalGroup(
            panelAnexosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnexosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Anexos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CodeBar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese la Descripcion");

        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyPressed(evt);
            }
        });

        grupoBotonesAnexo.add(jrVerStock);
        jrVerStock.setText("Ver Stock");
        jrVerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrVerStockActionPerformed(evt);
            }
        });

        grupoBotonesAnexo.add(jrVerCodigos);
        jrVerCodigos.setText("Ver + Codigos");
        jrVerCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrVerCodigosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkProveedores))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrVerStock)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrVerCodigos))
                                    .addComponent(panelAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProveedores)
                    .addComponent(jrVerStock)
                    .addComponent(jrVerCodigos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnexos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        if (evt.getClickCount() == 2) {
            seleccionarProducto(tableProductos.getSelectedRow());
        }
    }//GEN-LAST:event_tableProductosMouseClicked

    private void tfDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            filtrarProductos();
        }
    }//GEN-LAST:event_tfDescripcionKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        seleccionarProducto(tableProductos.getSelectedRow());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!panelAnexos.isVisible()) {
            activarPanelStock(true);
            jrVerStock.setSelected(true);
        } else {
            activarPanelStock(false);
            grupoBotonesAnexo.clearSelection();
        }
        dibujarTablaStock();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableProductosKeyReleased
        if (panelAnexos.isEnabled() && jrVerStock.isSelected()) {
            if (evt.getKeyCode() == KeyEvent.VK_UP) {
                verStock();
            }
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                verStock();
            }
        }
    }//GEN-LAST:event_tableProductosKeyReleased

    private void jrVerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrVerStockActionPerformed
        dibujarTablaStock();
    }//GEN-LAST:event_jrVerStockActionPerformed

    private void jrVerCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrVerCodigosActionPerformed
        dibujarTablaStock();
    }//GEN-LAST:event_jrVerCodigosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkProveedores;
    private javax.swing.ButtonGroup grupoBotonesAnexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton jrVerCodigos;
    private javax.swing.JRadioButton jrVerStock;
    private javax.swing.JPanel panelAnexos;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTable tablaStockCodigos;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables

    private void filtrarProductos() {
        dao = new ProductosDao();
        lista = dao.recuperarPorFiltro(tfDescripcion.getText());
        mtDproductos.setLista(lista);
    }

    private void seleccionarProducto(int index) {
        if (index < 0) {
            return;
        }
        Dproductos prod = lista.get(index);
        interfaceBuscadorProducto.setProducto(prod);
        dispose();
    }

    private void verStock() {
        mtVerStock = new ModeloTablaVerStock();
        tablaStockCodigos.setModel(mtVerStock);
        TableColumnModel columnModel = tablaStockCodigos.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(5);
        stockDao = new MovimientoStockDao();
        String id = tableProductos.getValueAt(tableProductos.getSelectedRow(), 0).toString();
        listaStock = stockDao.recuperarListaPorIdProducto(Long.parseLong(tableProductos.getValueAt(tableProductos.getSelectedRow(), 0).toString()));
        mtVerStock.setLista(listaStock);
    }

    private void activarPanelStock(boolean b) {
        panelAnexos.setVisible(b);
        tablaStockCodigos.setVisible(b);
        jrVerStock.setVisible(b);
        jrVerCodigos.setVisible(b);
    }

    private void dibujarTablaStock() {

        if (jrVerStock.isSelected()) {
            mtVerStock = new ModeloTablaVerStock();
            tablaStockCodigos.setModel(mtVerStock);
            TableColumnModel columnModel = tablaStockCodigos.getColumnModel();
            columnModel.getColumn(1).setPreferredWidth(5);
        }
        
        if (jrVerCodigos.isSelected()) {
            mtVerMasCodigos = new ModeloTablaMasCodigos();
            tablaStockCodigos.setModel(mtVerMasCodigos);
            TableColumnModel columnModel = tablaStockCodigos.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(115);
        }
    }
}
